openapi: 3.0.1
info:
  title: soap-array-of-objects-insert
  description: API Definition of implementation
  version: 1.0.0
servers:
- url: http://localhost:8290/array
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
