openapi: 3.0.1
info:
  title: implementation
  description: API Definition of implementation
  version: 1.0.0
servers:
  - url: "
http://localhost:8290/sd"
paths:
  /:
    post:
      responses:
        default:
          description: Default response
